### ISSUE TITLE
JSON files as virtual

### ISSUE THREAD

**Issue by kirill-konshin** [rollup/rollup-plugin-virtual#3]
I tried to slip a virtual for `pacakge.json` (in order to get version), but I failed:

```js
var json = require('rollup-plugin-json');
var virtual = require('rollup-plugin-virtual');

module.exports = {
  plugins: [
    json(),
    virtual({
        'package.json': JSON.stringify({
            version: require('./package.json').version
        })
    })
  ]
};
```

Results in

```
[!] Error: Unexpected token
virtual:/xxx/package.json (1:10)
1: {"version":"3.1.3"}
```

If I change it to

```js
var virtual = require('rollup-plugin-virtual');

module.exports = {
  plugins: [
    virtual({
        'package.json': 'export default ' + JSON.stringify({
            version: require('./package.json').version
        })
    })
  ]
};
```

I get

```
[!] TypeError: Cannot read property 'traceExport' of undefined
TypeError: Cannot read property 'traceExport' of undefined
    at Module.traceExport (/xxx/node_modules/rollup/dist/rollup.js:8504:17)
    at Object.keys.forEach.name (/xxx/node_modules/rollup/dist/rollup.js:10095:23)
    at Array.forEach (<anonymous>)
    at then.resolvedId (/xxx/node_modules/rollup/dist/rollup.js:10091:37)
    at <anonymous>
```

**Comment by Rich-Harris** [comment]
What happens if you put the `json` plugin *after* the `virtual` plugin?

**Comment by Rich-Harris** [comment]
Incidentally, there's no harm in importing the real package.json — everything but `version` will be tree-shaken away if you do this:

```js
import { version } from './package.json';
```

**Comment by kirill-konshin** [comment]
> What happens if you put the json plugin after the virtual plugin?

Nothing... same results

> will be tree-shaken away

What if I am not using ES6 modules notation? I only need to compile a set of commonjs ES5 modules into a browser build...

**Comment by Rich-Harris** [comment]
Ah, of course — virtual modules are ignored by other plugins. I'm afraid the workaround you came up with (prefixing the JSON with `export default`) is the only way this'll work — the output of this plugin needs to be JavaScript.

If you're not using ES6 modules notation, then, well, *you should be* 😀

**Comment by kirill-konshin** [comment]
Unfortunately, adding `export default` does not solve the issue. Like I said, I get weirdest error:

```
[!] TypeError: Cannot read property 'traceExport' of undefined
TypeError: Cannot read property 'traceExport' of undefined
    at Module.traceExport (/xxx/node_modules/rollup/dist/rollup.js:8504:17)
    at Object.keys.forEach.name (/xxx/node_modules/rollup/dist/rollup.js:10095:23)
    at Array.forEach (<anonymous>)
    at then.resolvedId (/xxx/node_modules/rollup/dist/rollup.js:10091:37)
    at <anonymous>
```

**Comment by Rich-Harris** [comment]
Works for me. Can you make a repro please?

**Comment by kirill-konshin** [comment]
https://github.com/ringcentral/ringcentral-js/blob/6a752c1150e572b7da8c1015e780f707364a7286/rollup.config.js

**Comment by kirill-konshin** [comment]
Bump

**Comment by kirill-konshin** [comment]
Bump

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We're also getting ready to move this plugin to a new monorepo for official plugins at https://github.com/rollup/plugins. This plugin and many others need some TLC. If this issue is still valid, please recreate it at the new monorepo. 

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
