### ISSUE TITLE
Doesn't work as entry?

### ISSUE THREAD

**Issue by developit** [rollup/rollup-plugin-virtual#4]
Not sure if I'm doing something awful here, but I had been using `rollup-plugin-memory` previously to alias my entry (so I could prune exports for certain bundles).  It doesn't appear to work with the latest Rollup, so I tried this plugin.

What I'm seeing is that it's not possible to use this to supply inline content for the entry:

```js
{
  input: {
    entry: '__entry__',
    plugins: [
      virtual({
        __entry__: `export { default } from '${entry}';`
      })
    ]
  }
}
```

Looks like rollup isn't using resolveId() for the entry?  I get this error:

> `ENOENT: no such file or directory, open '__entry__'`

**Comment by TrySound** [comment]
@developit I can't reproduce this. Can you provide a repo?

**Comment by TrySound** [comment]
I also deprecated memory plugin in favor of this one.

**Comment by Rich-Harris** [comment]
The `entry` option changed to `input` a few versions back, could that be related?

**Comment by TrySound** [comment]
Config should look like this.
```js
{
  input: '__entry__',
  plugins: [
    virtual({
      __entry__: `export { default } from '${entry}';`
    })
  ]
}
```

**Comment by developit** [comment]
I wasn't able to get that working. Instead I've switched to using `rollup-plugin-alias` with a physical entry file that imports the aliased one:

https://github.com/developit/microbundle/blob/master/src/index.js#L195-L200

**Comment by matthewmueller** [comment]
I ran into this as well, I found that [rollup-plugin-hypothetical](https://github.com/Permutatrix/rollup-plugin-hypothetical) supports entries.

```js
import hypothetical from 'rollup-plugin-hypothetical'
import browser from '../rollup/browser'
import { rollup } from 'rollup'

export default async function Browser(path: string, code?: string): Promise<string> {
  const plugins = []
  if (typeof code === 'string') {
    // if we have code, add it virtually
    plugins.push(hypothetical({ files: { [path]: code }, allowFallthrough: true }))
  }
  const config = await browser({ input: [path], plugins })
  const bundle = await rollup(config)
  const result = await bundle.generate(config.output)
  return result.output[0].code
}
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We're also getting ready to move this plugin to a new monorepo for official plugins at https://github.com/rollup/plugins. This plugin and many others need some TLC. If this issue is still valid, please recreate it at the new monorepo. 

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
