### ISSUE TITLE
valid replacement for rollup-plugin-memory

### ISSUE THREAD

**Issue by Announcement** [rollup/rollup-plugin-virtual#5]
how is this a valid plugin for rollup-plugin-memory, they do two different things.
rollup-plugin-memory allowed you to use files that have already been read as entry points and virtual does not.

**Comment by TrySound** [comment]
```js
import virtual from 'rollup-plugin-virtual';

export default {
  entry: '__entry__',
  // ...
  plugins: [
    virtual({
      '__entry__': 'export default 1'
    })
  ]
};
```
I guess we can add this recipe.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We're also getting ready to move this plugin to a new monorepo for official plugins at https://github.com/rollup/plugins. This plugin and many others need some TLC. If this issue is still valid, please recreate it at the new monorepo. 

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
