### ISSUE TITLE
Has trouble resolving basic imports

### ISSUE THREAD

**Issue by lastmjs** [rollup/rollup-plugin-virtual#6]
It seems even basic imports have trouble resolving. Here is my setup:

```javascript
const bundle = await rollup.rollup({
            input: '__entry__',
            plugins: [rollupPluginVirtual({
                __entry__: source
            })]
        });

const result = await bundle.generate({
            format: 'es'
        });
```

Is the setup above supposed to work?

**Comment by lastmjs** [comment]
The source is just the string of a file that I want to run through Rollup

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We're also getting ready to move this plugin to a new monorepo for official plugins at https://github.com/rollup/plugins. This plugin and many others need some TLC. If this issue is still valid, please recreate it at the new monorepo. 

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
