### ISSUE TITLE
Virtual entries are not processed by other plugins

### ISSUE THREAD

**Issue by antony** [rollup/rollup-plugin-virtual#7]
Hi,

I'm writing a completely dynamic svelte application where components are generated on the fly and imported into a virtual `__entry__`point.

I've noticed that virtual entries don't seem to be processed by any other plugins (in this case svelte). This unfortunately makes my task impossible.

An example is below:

```javascript
 'use strict'

 const virtual = require('rollup-plugin-virtual')
 const svelte = require('rollup-plugin-svelte')
 const rollup = require('rollup')

 const inputOptions = {
  input: '__entry__',
  plugins: [
    svelte({
      include: '**/*.html'
    }),
    virtual({
      '__entry__': `
        import App from '__app__/component.html'

        const app = new App({
          target: document.getElementsByTagName('body')[0]
        })
      `,
      '__app__/component.html': `
        <h1>Hello</h1>
      `
    })
  ]
}

const outputOptions = {
  file: 'bundle.js',
  format: 'iife'
}

return rollup
  .rollup(inputOptions)
  .then(bundle => {
    return bundle.generate(outputOptions)
  })
  .catch(e => {
    console.error(e)
  })
```

**Comment by antony** [comment]
I've discovered that this is due to the following line in `rollup-pluginutils`

https://github.com/rollup/rollup-pluginutils/blob/master/src/createFilter.js#L13

Not sure what the purpose of the null byte is in this plugin, but it seems to be preventing svelte from processing virtual entries...

**Comment by lemmabit** [comment]
@antony [rollup-plugin-hypothetical](https://github.com/Permutatrix/rollup-plugin-hypothetical) does about the same thing as this plugin but doesn't put those null characters in there. Maybe it will work.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We're also getting ready to move this plugin to a new monorepo for official plugins at https://github.com/rollup/plugins. This plugin and many others need some TLC. If this issue is still valid, please recreate it at the new monorepo. 

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
