### ISSUE TITLE
Redundant with rollup-plugin-hypothetical

### ISSUE THREAD

**Issue by lemmabit** [rollup/rollup-plugin-virtual#8]
rollup-plugin-virtual seems to implement functionality that already existed in one of my plugins, [rollup-plugin-hypothetical](https://github.com/Permutatrix/rollup-plugin-hypothetical).

hypothetical has a lot more maturity and features, though virtual currently has the advantage when it comes to awareness of Rollup's `\0` convention.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We're also getting ready to move this plugin to a new monorepo for official plugins at https://github.com/rollup/plugins. This plugin and many others need some TLC. If this issue is still valid, please recreate it at the new monorepo. 

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
