### ISSUE TITLE
Sourcemaps Appear Broken

### ISSUE THREAD

**Issue by curran** [rollup/rollup-plugin-virtual#9]
Greetings,

I'm using `rollup-plugin-virtual` in the context of a Web-based IDE, and I'm working on improving debugging support.

I tried enabling inline sourcemaps in the Rollup output configuration, but the resulting output is devoid of any file content. This is what the output looks like:

```
{
  "version": 3,
  "file": "index.js",
  "sources": [],
  "sourcesContent": [],
  "names": [],
  "mappings": ";;;;;;;;;"
}
```

The desired output would contain the content of `index.js`, and another module it imports from `message.js`.

I'm filing this issue to sort of put out feelers and see if this project is actively maintained, or if anyone has some ideas for how to solve this.

My hunch is that there's a part of the Rollup plugin API to do with sourcemaps that is not implemented in `rollup-plugin-virtual`, but I'm not 100% sure.

I plan to put together a minimal project setup that reproduces of this behavior shortly.

Related: https://github.com/Permutatrix/rollup-plugin-hypothetical#sourcemaps

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We're also getting ready to move this plugin to a new monorepo for official plugins at https://github.com/rollup/plugins. This plugin and many others need some TLC. If this issue is still valid, please recreate it at the new monorepo. 

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
